from gym.envs.registration import register

register(
    id='TrainEnvVariableStiffness-v6',
    entry_point='gym_custom.envs:TrainEnvVariableStiffnessV6',
)
register(
    id='TrainEnvVariableStiffnessAndPosture-v6',
    entry_point='gym_custom.envs:TrainEnvVariableStiffnessAndPostureV6',
)
register(
    id='VS-v6',
    entry_point='gym_custom.envs:VSV6',
)
register(
    id='VSAP-v6',
    entry_point='gym_custom.envs:VSAPV6',
)
register(
    id='TrainEnvVariableStiffness-v7',
    entry_point='gym_custom.envs:TrainEnvVariableStiffnessV7',
)
register(
    id='TrainEnvVariableStiffnessAndPosture-v7',
    entry_point='gym_custom.envs:TrainEnvVariableStiffnessAndPostureV7',
)
register(
    id='TrainEnvVariableStiffnessAndPostureAndSM-v7',
    entry_point='gym_custom.envs:TrainEnvVariableStiffnessAndPostureAndSMV7',
)
register(
    id='VS-v7',
    entry_point='gym_custom.envs:VSV7',
)
register(
    id='VSAP-v7',
    entry_point='gym_custom.envs:VSAPV7',
)
register(
    id='VSAPASM-v7',
    entry_point='gym_custom.envs:VSAPASMV7',
)
register(
    id='TrainEnvVariableStiffness-v8',
    entry_point='gym_custom.envs:TrainEnvVariableStiffnessV8',
)
register(
    id='TrainEnvVariableStiffnessAndPosture-v8',
    entry_point='gym_custom.envs:TrainEnvVariableStiffnessAndPostureV8',
)
register(
    id='TrainEnvVariableStiffnessAndPostureAndSM-v8',
    entry_point='gym_custom.envs:TrainEnvVariableStiffnessAndPostureAndSMV8',
)
register(
    id='VS-v8',
    entry_point='gym_custom.envs:VSV8',
)
register(
    id='VSAP-v8',
    entry_point='gym_custom.envs:VSAPV8',
)
register(
    id='VSAPASM-v8',
    entry_point='gym_custom.envs:VSAPASMV8',
)
