from gym_custom.envs.jk5_env_v6 import TrainEnvVariableStiffness as TrainEnvVariableStiffnessV6
from gym_custom.envs.jk5_env_v6 import TrainEnvVariableStiffnessAndPosture as TrainEnvVariableStiffnessAndPostureV6
from gym_custom.envs.jk5_env_v7 import TrainEnvVariableStiffness as TrainEnvVariableStiffnessV7
from gym_custom.envs.jk5_env_v7 import TrainEnvVariableStiffnessAndPosture as TrainEnvVariableStiffnessAndPostureV7
