from gym_custom.envs.jk5_env_v6 import TrainEnvVariableStiffness as TrainEnvVariableStiffnessV6
from gym_custom.envs.jk5_env_v6 import TrainEnvVariableStiffnessAndPosture as TrainEnvVariableStiffnessAndPostureV6
from gym_custom.envs.jk5_env_v6 import VS as VSV6
from gym_custom.envs.jk5_env_v6 import VSAP as VSAPV6

from gym_custom.envs.jk5_env_v7 import TrainEnvVariableStiffness as TrainEnvVariableStiffnessV7
from gym_custom.envs.jk5_env_v7 import TrainEnvVariableStiffnessAndPosture as TrainEnvVariableStiffnessAndPostureV7
from gym_custom.envs.jk5_env_v7 import TrainEnvVariableStiffnessAndPostureAndSM as TrainEnvVariableStiffnessAndPostureAndSMV7
from gym_custom.envs.jk5_env_v7 import VS as VSV7
from gym_custom.envs.jk5_env_v7 import VSAP as VSAPV7
from gym_custom.envs.jk5_env_v7 import VSAPAM as VSAPASMV7

from gym_custom.envs.jk5_env_v8 import TrainEnvVariableStiffness as TrainEnvVariableStiffnessV8
from gym_custom.envs.jk5_env_v8 import TrainEnvVariableStiffnessAndPosture as TrainEnvVariableStiffnessAndPostureV8
from gym_custom.envs.jk5_env_v8 import TrainEnvVariableStiffnessAndPostureAndSM as TrainEnvVariableStiffnessAndPostureAndSMV8
from gym_custom.envs.jk5_env_v8 import VS as VSV8
from gym_custom.envs.jk5_env_v8 import VSAP as VSAPV8
from gym_custom.envs.jk5_env_v8 import VSAPAM as VSAPASMV8
